/* =====================================================================
   KRISHIVIDYA — crops and varieties
   Fields: name, Marathi name, scientific name, category, season, note, flags
   flags: GI = Geographical Indication registered for Maharashtra produce;
          land = traditional landrace or heritage variety;
          wild = gathered from forests or field margins
   Seasons: kharif (June–Oct), rabi (Oct–Mar), summer, perennial, all
   ===================================================================== */
const CROP_CATS = {
  cereal: "Cereals", millet: "Millets", pulse: "Pulses", oilseed: "Oilseeds", fibre: "Fibre crops",
  vegetable: "Vegetables", wild: "Forest & wild greens", fruit: "Fruits", spice: "Spices & condiments", plantation: "Plantation & cash crops"
};
const Cr = (name, dev, sci, cat, season, note, flags = "") => ({ name, dev, sci, cat, season, note, flags: flags ? flags.split(" ") : [] });
const CROPS = [
  /* ---------- cereals ---------- */
  Cr("Rice", "भात / तांदूळ", "Oryza sativa", "cereal", "kharif", "The staple of Konkan, the Sahyadri hills and eastern Vidarbha. India has one of the world's richest collections of rice landraces."),
  Cr("Ambemohar rice", "आंबेमोहर", "Oryza sativa", "cereal", "kharif", "A short-grained rice from Mulshi and Maval (Pune) named for its mango-blossom fragrance. It is GI-registered.", "GI land"),
  Cr("Ajara Ghansal rice", "आजरा घनसाळ", "Oryza sativa", "cereal", "kharif", "A fragrant rice from Ajara taluka of Kolhapur, known for its aroma when cooked. It is GI-registered.", "GI land"),
  Cr("Wada Kolam rice", "वाडा कोलम", "Oryza sativa", "cereal", "kharif", "A fine, soft-textured rice from Wada in Palghar district, prized for daily meals.", "land"),
  Cr("Hill rice landraces", "डोंगरी भात वाण", "Oryza sativa", "cereal", "kharif", "Mahadev Koli and Thakar farmers of Akole and Junnar grow many local varieties such as Kalbhat, Jirvel and Raibhog, suited to hill terraces and heavy rain.", "land"),
  Cr("Salt-tolerant khar rice", "खार भात", "Oryza sativa", "cereal", "kharif", "Traditional varieties grown on reclaimed coastal khar lands, where ordinary rice would fail because of salinity.", "land"),
  Cr("Khapli wheat (emmer)", "खपली गहू", "Triticum dicoccum", "cereal", "rabi", "An ancient hulled wheat still grown in Satara, Sangli and Karnataka. It is valued for its fibre and is increasingly sought by health-conscious buyers.", "land"),
  Cr("Bansi wheat (durum)", "बन्सी गहू", "Triticum durum", "cereal", "rabi", "The traditional hard wheat of the Deccan, suited to rain-fed black soils and used for semolina and chapatis.", "land"),
  Cr("Bread wheat", "गहू", "Triticum aestivum", "cereal", "rabi", "The main irrigated wheat today; high-yielding varieties spread after the Green Revolution."),
  Cr("Maize", "मका", "Zea mays", "cereal", "kharif", "Brought to India from the Americas around the 16th century, maize is now a staple of the Bhil and Pawara hills and a major fodder crop."),
  Cr("Barley", "जव", "Hordeum vulgare", "cereal", "rabi", "Yava, the chief grain of the Rigveda, and one of the first crops grown at Mehrgarh. It is now a minor crop in Maharashtra."),
  /* ---------- millets ---------- */
  Cr("Jowar (sorghum)", "ज्वारी", "Sorghum bicolor", "millet", "kharif rabi", "The traditional staple of the Deccan. Its area in Maharashtra fell from 62.8 lakh ha in 1960-61 to 16.9 lakh ha in 2024-25."),
  Cr("Maldandi jowar", "मालदांडी ज्वारी", "Sorghum bicolor", "millet", "rabi", "The famous rabi jowar of Mangalvedha (Solapur), grown on stored soil moisture. The M-35-1 variety was selected from it, and Mangalvedha jowar is GI-registered.", "GI land"),
  Cr("Dagdi and Shalu jowar", "दगडी व शाळू ज्वारी", "Sorghum bicolor", "millet", "rabi", "Local rabi types with bold white grain, traditionally preferred for bhakri.", "land"),
  Cr("Hurda jowar", "हुरडा ज्वारी", "Sorghum bicolor", "millet", "rabi", "Sweet varieties harvested at the milky stage and roasted on coals for winter hurda parties in the fields.", "land"),
  Cr("Bajra (pearl millet)", "बाजरी", "Pennisetum glaucum", "millet", "kharif", "The hardiest cereal of the dry Deccan, grown in Ahilyanagar, Pune, Nashik, Dhule and Beed."),
  Cr("Nachni (finger millet)", "नाचणी / नागली", "Eleusine coracana", "millet", "kharif", "Rich in calcium and grown on the slopes of the Sahyadri and Konkan hills. Nachni bhakri and ambil are everyday foods."),
  Cr("Varai (small millet)", "वरई / भगर", "Panicum and Echinochloa spp.", "millet", "kharif", "A hill millet of Nashik, Palghar and Ahilyanagar. Its grain, sold as bhagar, is widely eaten on fasting days. The local name is applied to more than one small millet, so botanists identify it field by field.", "land"),
  Cr("Sava", "सावा", "Echinochloa frumentacea", "millet", "kharif", "A quick-maturing hill millet of the Sahyadri tribes.", "land"),
  Cr("Rala (foxtail millet)", "राळा", "Setaria italica", "millet", "kharif", "Priyangu of the Yajurveda. Once common across the Deccan, it now survives mainly in tribal and dryland pockets.", "land"),
  Cr("Kodo millet", "कोदो / कोद्रा", "Paspalum scrobiculatum", "millet", "kharif", "A drought-hardy millet of Melghat and Gadchiroli, grown by Korku and Gond farmers.", "land"),
  Cr("Kutki", "कुटकी", "Panicum sumatrense", "millet", "kharif", "A small millet of central India's forest villages, eaten as rice or gruel.", "land"),
  Cr("Proso millet", "चेना", "Panicum miliaceum", "millet", "kharif summer", "A fast-growing millet that fits into short seasons.", "land"),
  /* ---------- pulses ---------- */
  Cr("Tur (pigeon pea)", "तूर", "Cajanus cajan", "pulse", "kharif", "India is its centre of origin. Tur is usually intercropped with jowar, cotton or soybean in Vidarbha and Marathwada."),
  Cr("Navapur tur", "नवापूर तूर", "Cajanus cajan", "pulse", "kharif", "A local tur from Navapur (Nandurbar), prized for the flavour of its dal. It is GI-registered.", "GI land"),
  Cr("Harbhara (chickpea)", "हरभरा", "Cicer arietinum", "pulse", "rabi", "The main rabi pulse of Maharashtra, grown on residual moisture in black soils."),
  Cr("Mung (green gram)", "मूग", "Vigna radiata", "pulse", "kharif", "Mudga of the Vedas. A short-duration pulse that fits before rabi crops."),
  Cr("Udid (black gram)", "उडीद", "Vigna mungo", "pulse", "kharif", "Masha of the Vedas, used for papad and fermented foods."),
  Cr("Matki (moth bean)", "मटकी", "Vigna aconitifolia", "pulse", "kharif", "Extremely drought-tolerant and traditionally mixed with bajra. Sprouted matki is the base of misal."),
  Cr("Kulith (horse gram)", "कुळीथ", "Macrotyloma uniflorum", "pulse", "kharif rabi", "A hardy hill pulse of the Konkan and Sahyadri, eaten as kulith pithla and valued in traditional medicine.", "land"),
  Cr("Chavli (cowpea)", "चवळी", "Vigna unguiculata", "pulse", "kharif", "Grown for grain, green pods and fodder."),
  Cr("Wal (field bean)", "वाल", "Lablab purpureus", "pulse", "rabi", "A Konkan speciality grown in paddy fields after the rice harvest; dalimbi usal is made from it.", "land"),
  Cr("Pavta and ghevda", "पावटा व घेवडा", "Lablab purpureus", "pulse", "rabi", "Bean types grown for green pods and grain."),
  Cr("Waghya ghevada", "वाघ्या घेवडा", "Phaseolus vulgaris", "pulse", "kharif", "A striped bean of Satara district, named for its tiger-like markings. It is GI-registered.", "GI land"),
  Cr("Masoor (lentil)", "मसूर", "Lens culinaris", "pulse", "rabi", "Masura of the Yajurveda, found at Harappan and Chalcolithic Deccan sites."),
  Cr("Lakhori (grass pea)", "लाख / लाखोळी", "Lathyrus sativus", "pulse", "rabi", "A very hardy pulse sown into standing rice in Vidarbha. Eating it in large amounts can cause lathyrism, so low-toxin varieties have been bred.", "land"),
  Cr("Watana (field pea)", "वाटाणा", "Pisum sativum", "pulse", "rabi", "Grown for green peas and dry grain; peas were found at Inamgaon."),
  Cr("Soybean", "सोयाबीन", "Glycine max", "pulse", "kharif", "A modern crop introduced on a large scale from the 1970s, now the leading kharif crop of Marathwada and western Vidarbha."),
  /* ---------- oilseeds ---------- */
  Cr("Groundnut", "भुईमूग", "Arachis hypogaea", "oilseed", "kharif summer", "Brought from South America. Its area in Maharashtra fell from 10.8 to 2.5 lakh ha between 1960-61 and 2024-25."),
  Cr("Til (sesame)", "तीळ", "Sesamum indicum", "oilseed", "kharif", "Tila of the Vedas, one of the world's oldest oilseeds. Sesame and jaggery are exchanged at Makar Sankranti."),
  Cr("Kardai (safflower)", "करडई", "Carthamus tinctorius", "oilseed", "rabi", "A thorny, drought-hardy rabi oilseed; Maharashtra has long been one of India's main producers."),
  Cr("Karale (niger)", "कारळे", "Guizotia abyssinica", "oilseed", "kharif", "A tribal-belt oilseed of the Sahyadri and Satpuda, used for oil and chutney. It is in steep decline.", "land"),
  Cr("Jawas (linseed)", "जवस", "Linum usitatissimum", "oilseed", "rabi", "Grown in Vidarbha and Marathwada; jawas chutney is a traditional food.", "land"),
  Cr("Sunflower", "सूर्यफूल", "Helianthus annuus", "oilseed", "rabi summer", "A modern oilseed that spread from the 1970s."),
  Cr("Castor", "एरंड", "Ricinus communis", "oilseed", "kharif", "Grown on field borders; the oil lit village lamps and lubricated cart axles."),
  Cr("Mustard", "मोहरी", "Brassica juncea", "oilseed", "rabi", "A minor crop in Maharashtra, grown mixed with rabi crops."),
  /* ---------- fibre ---------- */
  Cr("Desi cotton", "देशी कापूस", "Gossypium arboreum", "fibre", "kharif", "India's native cotton, grown here for at least 5,000 years. It needs few inputs and resists pests, though its fibre is shorter; efforts to revive it are underway.", "land"),
  Cr("Hybrid and Bt cotton", "संकरित कापूस", "Gossypium hirsutum", "fibre", "kharif", "American cotton, first hybrids and since 2002 Bt varieties, now covers most of Vidarbha's and Marathwada's cotton area."),
  Cr("Ambadi (kenaf)", "अंबाडी", "Hibiscus cannabinus", "fibre", "kharif", "Grown for fibre rope and for its sour leaves, which are cooked as a vegetable.", "land"),
  Cr("Tag (sunn hemp)", "ताग", "Crotalaria juncea", "fibre", "kharif", "A fibre crop that is also one of the best green manures.", "land"),
  /* ---------- vegetables ---------- */
  Cr("Brinjal", "वांगी", "Solanum melongena", "vegetable", "all", "India is a centre of brinjal diversity, and nearly every district has its own local types."),
  Cr("Jalgaon bharit brinjal", "जळगाव भरीत वांगी", "Solanum melongena", "vegetable", "rabi", "Large, round brinjals of Jalgaon, roasted for bharit. They are GI-registered.", "GI land"),
  Cr("Onion", "कांदा", "Allium cepa", "vegetable", "kharif rabi", "Maharashtra is India's largest onion producer, and Lasalgaon in Nashik is the country's largest onion market."),
  Cr("Lasalgaon onion", "लासलगाव कांदा", "Allium cepa", "vegetable", "rabi", "A pungent onion with good storage life, marketed from Lasalgaon. It is GI-registered.", "GI"),
  Cr("Alibag white onion", "अलिबाग पांढरा कांदा", "Allium cepa", "vegetable", "rabi", "A mild white onion from Raigad, valued for its medicinal reputation. It is GI-registered.", "GI land"),
  Cr("Bhendi (okra)", "भेंडी", "Abelmoschus esculentus", "vegetable", "kharif summer", "A native of the tropics widely grown in home gardens."),
  Cr("Gawar (cluster bean)", "गवार", "Cyamopsis tetragonoloba", "vegetable", "kharif", "A drought-tolerant legume of dry areas."),
  Cr("Shevga (drumstick)", "शेवगा", "Moringa oleifera", "vegetable", "perennial", "A native tree whose pods, leaves and flowers are all eaten. It is highly nutritious."),
  Cr("Dudhi (bottle gourd)", "दुधी भोपळा", "Lagenaria siceraria", "vegetable", "all", "Among the earliest cultivated plants. Dried gourds once served as containers and floats."),
  Cr("Lal bhopla (pumpkin)", "लाल भोपळा", "Cucurbita moschata", "vegetable", "kharif", "Stores for months and grows on field borders and roofs."),
  Cr("Karle (bitter gourd)", "कारले", "Momordica charantia", "vegetable", "kharif", "Grown on bamboo trellises across the state."),
  Cr("Kartoli (spiny gourd)", "करटोली", "Momordica dioica", "vegetable", "kharif", "A monsoon vegetable gathered from hedges and forest edges.", "wild"),
  Cr("Ghosale, dodka and padwal", "घोसाळे, दोडका, पडवळ", "Luffa spp., Trichosanthes cucumerina", "vegetable", "kharif", "Gourds grown on trellises in monsoon kitchen gardens."),
  Cr("Kakdi (cucumber)", "काकडी", "Cucumis sativus", "vegetable", "kharif summer", "India is the cucumber's home; local types are grown in riverbeds and field borders."),
  Cr("Methi (fenugreek)", "मेथी", "Trigonella foenum-graecum", "vegetable", "rabi", "Grown for leaves and seed."),
  Cr("Chuka and chakwat", "चुका व चाकवत", "Rumex vesicarius, Chenopodium album", "vegetable", "rabi", "Tangy leafy greens that grow in and around rabi fields."),
  Cr("Rajgira (amaranth)", "राजगिरा", "Amaranthus spp.", "vegetable", "kharif", "Grown for greens and grain; the popped grain is a fasting food."),
  Cr("Alu (colocasia)", "अळू", "Colocasia esculenta", "vegetable", "kharif", "Leaves are used for alu vadi and the corms are cooked. It grows well in Konkan and near wells."),
  Cr("Suran (elephant foot yam)", "सुरण", "Amorphophallus paeoniifolius", "vegetable", "kharif", "A tuber of Konkan and home gardens."),
  Cr("Ratale (sweet potato)", "रताळे", "Ipomoea batatas", "vegetable", "rabi", "Eaten on fasting days; also grown on residual moisture."),
  Cr("Mirchi (chilli)", "मिरची", "Capsicum annuum", "vegetable", "kharif", "Brought from the Americas in the 16th century, chilli became central to Indian food. Nandurbar has a major chilli market."),
  Cr("Bhiwapur chilli", "भिवापूर मिरची", "Capsicum annuum", "vegetable", "kharif", "A deep-red chilli from Bhiwapur in Nagpur district. It is GI-registered.", "GI land"),
  /* ---------- forest & wild greens ---------- */
  Cr("Tarota", "टाकळा / तरोटा", "Senna tora", "wild", "kharif", "The first monsoon green gathered from fallow land; its seeds are also used in traditional medicine.", "wild"),
  Cr("Kurdu", "कुरडू", "Celosia argentea", "wild", "kharif", "Tender leaves cooked as a monsoon vegetable.", "wild"),
  Cr("Shevla", "शेवळा", "Amorphophallus commutatus", "wild", "kharif", "A Konkan monsoon delicacy, cooked with kakad fruit to remove its itchiness.", "wild"),
  Cr("Bharangi", "भारंगी", "Clerodendrum serratum", "wild", "kharif", "Leaves eaten as a monsoon vegetable in tribal villages.", "wild"),
  Cr("Kavla and pathri", "कवळा व पाथरी", "Various", "wild", "kharif", "Wild greens gathered by women of the Sahyadri tribes. Maharashtra's annual ranbhaji festivals celebrate this knowledge.", "wild"),
  Cr("Mahua flowers", "मोहफुले", "Madhuca longifolia", "wild", "summer", "Collected in spring by Gond, Korku and Bhil families in Vidarbha, dried for food and sold. The seeds yield oil.", "wild"),
  Cr("Tendu", "तेंदू", "Diospyros melanoxylon", "wild", "summer", "Leaves are collected for bidi wrappers, an important seasonal income in Gadchiroli, Gondia and Chandrapur.", "wild"),
  Cr("Charoli", "चारोळी", "Buchanania lanzan", "wild", "summer", "Seeds from a forest tree, gathered by tribal families and used in sweets.", "wild"),
  Cr("Bamboo shoots", "बांबूचे कोंब", "Dendrocalamus strictus", "wild", "kharif", "Tender monsoon shoots eaten fresh or pickled in forest villages.", "wild"),
  /* ---------- fruits ---------- */
  Cr("Alphonso (Hapus) mango", "हापूस आंबा", "Mangifera indica", "fruit", "summer", "Grown on the laterite slopes of the Konkan. It is GI-registered.", "GI"),
  Cr("Marathwada Kesar mango", "मराठवाडा केशर आंबा", "Mangifera indica", "fruit", "summer", "A saffron-fleshed mango adapted to the drier plateau. It is GI-registered.", "GI"),
  Cr("Rayval and gavthi mangoes", "रायवळ / गावठी आंबा", "Mangifera indica", "fruit", "summer", "Thousands of village seedling mangoes, each tree unique, used for pickles, aamras and grafting stock.", "land"),
  Cr("Jackfruit", "फणस", "Artocarpus heterophyllus", "fruit", "summer", "A Konkan staple whose seeds, pulp and unripe fruit are all eaten."),
  Cr("Jamun", "जांभूळ", "Syzygium cumini", "fruit", "summer", "A native fruit tree of village commons; Bahadoli in Palghar is known for its large jamun.", "land"),
  Cr("Karvand", "करवंद", "Carissa carandas", "fruit", "summer", "A wild hedge fruit of the Sahyadri, called the 'black pearl of the hills'.", "wild"),
  Cr("Bor (Indian jujube)", "बोर", "Ziziphus mauritiana", "fruit", "rabi", "A hardy native fruit of dry lands, eaten fresh and dried."),
  Cr("Ranmeva (wild fruits)", "रानमेवा", "Various", "fruit", "summer", "A collective name for forest fruits such as tembhurni, aain, alu and umbar gathered in summer.", "wild"),
  Cr("Nagpur orange", "नागपुरी संत्री", "Citrus reticulata", "fruit", "rabi", "The mandarin of Nagpur, Amravati and Wardha. It is GI-registered.", "GI"),
  Cr("Jalna sweet orange", "जालना मोसंबी", "Citrus sinensis", "fruit", "rabi", "The mosambi of Jalna and Marathwada. It is GI-registered.", "GI"),
  Cr("Solapur pomegranate", "सोलापूर डाळिंब", "Punica granatum", "fruit", "all", "Bhagwa and Ganesh varieties grow in the dry districts of Solapur, Sangli and Ahilyanagar. The Solapur pomegranate is GI-registered.", "GI"),
  Cr("Nashik grapes", "नाशिक द्राक्षे", "Vitis vinifera", "fruit", "rabi", "The grape and wine capital of India. Nashik grapes are GI-registered.", "GI"),
  Cr("Sangli raisins", "सांगली बेदाणे", "Vitis vinifera", "fruit", "rabi", "Sun-dried and shade-dried raisins from Sangli and Tasgaon. They are GI-registered.", "GI"),
  Cr("Jalgaon banana", "जळगाव केळी", "Musa spp.", "fruit", "perennial", "Grand Naine and Basrai bananas of the Tapi valley. Jalgaon banana is GI-registered.", "GI"),
  Cr("Purandar fig", "पुरंदर अंजीर", "Ficus carica", "fruit", "rabi", "Grown on the dry hills of Purandar (Pune). It is GI-registered.", "GI"),
  Cr("Beed custard apple", "बीड सीताफळ", "Annona squamosa", "fruit", "kharif", "Grows almost wild on the rocky hills of Beed and Balaghat. It is GI-registered.", "GI"),
  Cr("Dahanu Gholvad chikoo", "डहाणू घोलवड चिकू", "Manilkara zapota", "fruit", "all", "Sapota from the coastal belt of Palghar. It is GI-registered.", "GI"),
  Cr("Mahabaleshwar strawberry", "महाबळेश्वर स्ट्रॉबेरी", "Fragaria × ananassa", "fruit", "rabi", "Grown on the cool plateau of Mahabaleshwar and Panchgani. It is GI-registered.", "GI"),
  Cr("Guava", "पेरू", "Psidium guajava", "fruit", "rabi", "Introduced by the Portuguese; now grown across the state."),
  Cr("Amla", "आवळा", "Phyllanthus emblica", "fruit", "rabi", "A native fruit rich in vitamin C, used in food and Ayurveda."),
  Cr("Tamarind", "चिंच", "Tamarindus indica", "fruit", "rabi", "A long-lived shade tree of villages and roadsides, and a source of income for forest families."),
  Cr("Kokum", "कोकम / रातांबा", "Garcinia indica", "fruit", "summer", "A native tree of the Western Ghats. Its dried rind sours curries, and solkadhi is made from it. Kokum of the Konkan is GI-registered.", "GI"),
  /* ---------- spices ---------- */
  Cr("Turmeric", "हळद", "Curcuma longa", "spice", "kharif", "A native of India used in food, ritual and medicine. Sangli and the Basmat market in Hingoli are major trade centres."),
  Cr("Sangli turmeric", "सांगली हळद", "Curcuma longa", "spice", "kharif", "Traditionally stored in underground pits (pev) that keep it for years. It is GI-registered.", "GI"),
  Cr("Waigaon turmeric", "वायगाव हळद", "Curcuma longa", "spice", "kharif", "A deep-coloured, high-curcumin turmeric of Waigaon in Wardha district. It is GI-registered.", "GI land"),
  Cr("Ginger", "आले", "Zingiber officinale", "spice", "kharif", "Grown in Aurangabad, Jalna and Satara."),
  Cr("Garlic", "लसूण", "Allium sativum", "spice", "rabi", "A rabi crop of Nashik, Pune and Marathwada."),
  Cr("Coriander", "धणे / कोथिंबीर", "Coriandrum sativum", "spice", "rabi", "Grown for seed and fresh leaves."),
  Cr("Black pepper", "मिरी", "Piper nigrum", "spice", "perennial", "A native of the Western Ghats, grown on trees in Konkan orchards."),
  Cr("Kolhapur jaggery", "कोल्हापुरी गूळ", "Saccharum officinarum", "spice", "perennial", "Made by boiling sugarcane juice in open pans at village gurhals. It is GI-registered.", "GI"),
  /* ---------- plantation & cash ---------- */
  Cr("Sugarcane", "ऊस", "Saccharum officinarum", "plantation", "perennial", "India is one of the homes of sugar: the word 'sugar' traces back to the Sanskrit sharkara. Maharashtra's co-operative sugar factories began at Pravaranagar in 1950."),
  Cr("Coconut", "नारळ", "Cocos nucifera", "plantation", "perennial", "The 'kalpavriksha' of the Konkan, used for food, oil, rope, thatch and toddy."),
  Cr("Cashew", "काजू", "Anacardium occidentale", "plantation", "perennial", "Brought by the Portuguese; Vengurla cashew of Sindhudurg is GI-registered.", "GI"),
  Cr("Areca nut", "सुपारी", "Areca catechu", "plantation", "perennial", "Grown in shaded Konkan orchards (agar) alongside coconut, banana and pepper."),
  Cr("Betel vine", "विड्याची पाने", "Piper betle", "plantation", "perennial", "Grown in shaded gardens (paanmala) of Vasai, Ramtek and elsewhere; the leaves are offered in rituals.")
];