/* =====================================================================
   KRISHIVIDYA — core helpers + history of Indian agricultural knowledge
   Evidence tags:
     archaeology — excavated physical evidence
     text        — stated in a classical or historical text
     history     — documented historical event or record
     policy      — government law, scheme or census
     science     — modern scientific study or validation
   Dates for ancient texts are scholarly estimates; where scholars
   disagree, the range is given in the entry itself.
   ===================================================================== */
const T = (en, mr, hi) => ({ en, mr, hi });        // fully translated text
const D = (en, dev) => ({ en, mr: dev, hi: dev });  // proper noun with a Devanagari form

const ERAS = [
  { id: "prehistoric", label: "Prehistory & Harappan", range: "c. 7000 – 1500 BCE", icon: "🏺" },
  { id: "vedic", label: "Vedic period", range: "c. 1500 – 500 BCE", icon: "🔥" },
  { id: "classical", label: "Classical India", range: "c. 500 BCE – 600 CE", icon: "📜" },
  { id: "earlymedieval", label: "Early medieval", range: "600 – 1200 CE", icon: "🛕" },
  { id: "medieval", label: "Medieval & Maratha", range: "1200 – 1818", icon: "⚔️" },
  { id: "colonial", label: "Colonial period", range: "1818 – 1947", icon: "🚂" },
  { id: "independent", label: "Independent India", range: "1947 – 2000", icon: "🇮🇳" },
  { id: "now", label: "21st century", range: "2000 – 2026", icon: "🛰️" }
];

/* y = label shown; s = sort year (negative = BCE); mh = Maharashtra-specific */
const TIMELINE = [
  { s: -7000, y: "c. 7000 BCE", era: "prehistoric", tag: "archaeology", title: "Farming begins at Mehrgarh",
    text: "Excavations at Mehrgarh, at the foot of the Bolan Pass, show some of the earliest farming in South Asia. People there grew barley and wheat and herded zebu (humped) cattle, sheep and goats." },
  { s: -5500, y: "c. 6000–5000 BCE", era: "prehistoric", tag: "archaeology", title: "The earliest evidence of cotton",
    text: "Mineralised cotton fibres found inside a copper bead at Mehrgarh are among the oldest known traces of cotton use anywhere in the world. India went on to become the world's first great cotton-weaving civilisation." },
  { s: -2800, y: "c. 2800 BCE", era: "prehistoric", tag: "archaeology", title: "A ploughed field at Kalibangan",
    text: "At Kalibangan in Rajasthan, archaeologists found a field with furrows crossing at right angles. It is the oldest ploughed field excavated in the world, and its pattern closely resembles the way farmers in the region still sow two crops together, such as mustard with gram." },
  { s: -2500, y: "c. 2600–1900 BCE", era: "prehistoric", tag: "archaeology", title: "Harappan water engineering",
    text: "Harappan cities stored and managed water on a large scale. Dholavira in Kutch had a series of stone-cut reservoirs, and Lothal is often identified as a dockyard. Seals from this period depict the humped bull, the buffalo and the elephant." },
  { s: -1500, y: "c. 1600–1300 BCE", era: "prehistoric", mh: true, tag: "archaeology", title: "Daimabad: a farming village on the Pravara",
    text: "Daimabad in Ahilyanagar district is one of the largest Chalcolithic sites in the Deccan. A hoard of bronze objects found there includes a chariot drawn by two bullocks, along with a buffalo, an elephant and a rhinoceros." },
  { s: -1300, y: "c. 1400–1000 BCE", era: "prehistoric", mh: true, tag: "archaeology", title: "Inamgaon: irrigation in the Deccan",
    text: "At Inamgaon on the Ghod river in Pune district, excavators of the Jorwe culture found traces of an embankment and a channel built to divert floodwater to fields. Villagers there grew barley, wheat, lentils, peas and jowar, and kept cattle, sheep and goats." },
  { s: -1400, y: "c. 1500–1200 BCE", era: "vedic", tag: "text", title: "The Rigveda honours the field and the plough",
    text: "The Kshetrapati hymn (Rigveda 4.57) is addressed to the Lord of the Field. It asks for blessings on the ploughshare, the ploughman and the oxen, and invokes Sita, the furrow, to yield abundant crops. Other hymns refer to wells (avata) worked with wheels and buckets, and to irrigation channels (kulya)." },
  { s: -1350, y: "c. 1500–1200 BCE", era: "vedic", tag: "text", title: "“Play not with dice; cultivate your field”",
    text: "In Rigveda 10.34, a gambler who has lost everything receives this advice: give up dice, cultivate your field, and delight in the wealth it brings. The line (akṣair mā dīvyaḥ kṛṣim it kṛṣasva) is one of the oldest recorded statements that honest farming is the foundation of a good life." },
  { s: -1300, y: "c. 1500–1200 BCE", era: "vedic", tag: "text", title: "The hymn to the rivers",
    text: "The Nadistuti hymn (Rigveda 10.75) praises the rivers of the north-west, from the Ganga and Yamuna to the Sindhu. It is an early example of the sacred place that rivers hold in Indian life, as givers of water, fertile soil and food." },
  { s: -1000, y: "c. 1000 BCE", era: "vedic", tag: "text", title: "The Yajurveda lists India's grains",
    text: "The Vajasaneyi Samhita of the Yajurveda (18.12) lists rice (vrihi), barley (yava), black gram (masha), sesame (tila), green gram (mudga), wheat (godhuma), lentil (masura) and several millets, including priyangu (foxtail millet) and shyamaka. It is one of the earliest crop lists in any language." },
  { s: -900, y: "c. 1000–800 BCE", era: "vedic", tag: "text", title: "The Atharvaveda's hymn to the Earth",
    text: "The Prithvi Sukta (Atharvaveda 12.1) praises the Earth as a mother who nourishes all living beings and asks that people take from her without wounding her. The Atharvaveda also contains charms for rain, for protecting cattle, and for driving away pests from crops." },
  { s: -800, y: "c. 800 BCE", era: "vedic", tag: "text", title: "The four operations of farming",
    text: "The Shatapatha Brahmana (1.6.1.3) sums up farming in four words: ploughing, sowing, reaping and threshing. The Brahmanas also describe ceremonial ploughing with large teams of oxen and name the seasons for sowing barley and rice." },
  { s: -450, y: "c. 5th–4th century BCE", era: "classical", tag: "text", title: "Panini's grammar names fields by their crops",
    text: "Panini's Ashtadhyayi, the great Sanskrit grammar, gives special word forms for fields suited to particular crops, such as a field fit for rice or for barley. It shows how precisely early Indians classified land." },
  { s: -350, y: "c. 4th century BCE onward", era: "classical", tag: "text", title: "Kautilya's Arthashastra organises farming as statecraft",
    text: "The Arthashastra, compiled over several centuries, describes a Superintendent of Agriculture (Sitadhyaksha) who kept seeds, arranged labour and measured rainfall with a standard gauge. It records the rain expected in different regions, including Ashmaka on the Godavari in present-day Maharashtra. It also describes superintendents for cattle, horses and elephants." },
  { s: -300, y: "c. 300 BCE", era: "classical", tag: "text", title: "Megasthenes observes two harvests a year",
    text: "Megasthenes, the Greek envoy at the Mauryan court, wrote that Indian soils yielded two harvests a year, one with the summer rains and one in winter. He also noted that farmers were left undisturbed even in times of war." },
  { s: -250, y: "c. 3rd century BCE", era: "classical", tag: "history", title: "Ashoka's edicts: wells, trees and care for animals",
    text: "Ashoka's second Rock Edict records that he arranged medical treatment for both people and animals, and had wells dug and trees planted along roads. Other edicts restrict the killing of certain animals." },
  { s: -300, y: "c. 300 BCE – 455 CE", era: "classical", tag: "history", title: "The Sudarshana lake at Girnar",
    text: "An inscription of the Saka ruler Rudradaman (150 CE) at Junagadh records that the Sudarshana reservoir was first built under Chandragupta Maurya, improved under Ashoka, and repaired by Rudradaman after a storm burst its dam. It was repaired again under Skandagupta in 455–456 CE." },
  { s: -100, y: "c. 1st century BCE – 3rd century CE", era: "classical", mh: true, tag: "text", title: "The Satavahanas and the Gatha Saptashati",
    text: "The Satavahana kings ruled the Deccan from Pratishthana (Paithan) on the Godavari. The Gatha Saptashati, an anthology of Maharashtri Prakrit verse attributed to King Hala, portrays village life in vivid detail: cotton and rice fields, threshing floors, herders and the monsoon. Inscriptions of the period record gifts of cows and land." },
  { s: 0, y: "c. 300 BCE – 300 CE", era: "classical", tag: "text", title: "Sangam poetry maps five landscapes",
    text: "Tamil Sangam poetry divides land into five tinai: hills (kurinji), pastoral forest (mullai), river-fed farmland (marutham), coast (neithal) and arid land (palai). Each has its own crops, animals, people and moods. It is an early ecological classification of land use." },
  { s: 150, y: "c. 2nd century CE", era: "classical", tag: "history", title: "Kallanai, the Grand Anicut",
    text: "The Chola king Karikala is credited with building the Kallanai, a stone weir across the Kaveri. It is one of the oldest water-diversion structures in the world that is still in use, and it has fed the delta's paddy fields for nearly two thousand years." },
  { s: 450, y: "c. 5th century CE", era: "classical", tag: "text", title: "The Tirukkural: the world follows the plough",
    text: "Tiruvalluvar devotes a chapter of the Tirukkural to farming. Its opening couplet says that however the world may wander, it must follow the plough, because farming feeds all other work." },
  { s: 550, y: "6th century CE", era: "classical", tag: "text", title: "Varahamihira's Brihat Samhita",
    text: "Varahamihira's encyclopaedic Brihat Samhita contains chapters on forecasting the monsoon from signs in the sky months in advance (garbha lakshana), on finding underground water from plants, soils and termite mounds (dakargala), on the care of trees (vrikshayurveda), and on judging cattle by their features." },
  { s: 700, y: "dated between c. 500 and 1100 CE", era: "earlymedieval", tag: "text", title: "Krishi-Parashara, a farmer's manual",
    text: "Krishi-Parashara is a Sanskrit manual devoted wholly to farming. It covers rain forecasting, the parts of the plough, the management of cattle sheds, manuring, seed collection and storage, and the calendar of rice cultivation. Scholars date it anywhere between about 500 and 1100 CE." },
  { s: 800, y: "c. 8th–10th century CE", era: "earlymedieval", tag: "text", title: "Kashyapiya Krishisukti",
    text: "Attributed to the sage Kashyapa, this text describes rice farming in detail: preparing nurseries, transplanting, managing water, and protecting crops from pests. It also stresses that rulers should help farmers." },
  { s: 1000, y: "c. 1000 CE", era: "earlymedieval", tag: "text", title: "Surapala's Vrikshayurveda",
    text: "Surapala's Vrikshayurveda, the Science of Plant Life, covers seed treatment, grafting, irrigation, plant diseases and nutrition. It describes kunapajala, a fermented liquid manure made from animal remains, which modern researchers have studied as an organic plant-growth promoter." },
  { s: 1025, y: "1025 CE", era: "earlymedieval", tag: "text", title: "Lokopakara in Kannada",
    text: "Chavundaraya II wrote the Lokopakara (For the Benefit of the People), a Kannada encyclopaedia with sections on tree-planting, finding groundwater and treating plant diseases. It shows that agricultural knowledge was also written in regional languages." },
  { s: 1131, y: "1131 CE", era: "earlymedieval", mh: true, tag: "text", title: "Manasollasa of Someshvara III",
    text: "The Chalukya king Someshvara III compiled the Manasollasa, an encyclopaedia covering horticulture, irrigation, the care of horses and elephants, and the breeding and training of dogs. The Chalukya kingdom included much of present-day Maharashtra." },
  { s: 1350, y: "13th–14th century", era: "medieval", tag: "text", title: "Upavanavinoda on gardens and orchards",
    text: "Sarngadhara's Upavanavinoda is a treatise on arboriculture. It classifies soils, describes watering schedules and grafting, and explains how to treat sick trees." },
  { s: 1500, y: "c. 1500s", era: "medieval", tag: "history", title: "The Persian wheel spreads across the north",
    text: "The araghatta, a wheel carrying a chain of pots to lift water from wells, was known in India from early times. The geared Persian wheel, driven by bullocks, became widespread in northern India in this period, and Babur described it in his memoirs." },
  { s: 1595, y: "1590s", era: "medieval", tag: "history", title: "The Ain-i-Akbari records crops and revenue",
    text: "Abul Fazl's Ain-i-Akbari lists the crops of each province, their yields and prices, and the revenue system of Raja Todar Mal, which was based on careful measurement of land. It is a rich record of what India grew four centuries ago." },
  { s: 1610, y: "early 1600s", era: "medieval", mh: true, tag: "history", title: "Malik Ambar's land settlement in the Deccan",
    text: "Malik Ambar, the regent of the Ahmadnagar Sultanate, classified land by fertility and fixed revenue accordingly. This settlement shaped later Deccan revenue systems. He also founded Khadki, the city now called Chhatrapati Sambhajinagar, and gave it an underground water-supply system (nahar)." },
  { s: 1673, y: "17th century", era: "medieval", mh: true, tag: "history", title: "Chhatrapati Shivaji Maharaj protects the farmer",
    text: "Chhatrapati Shivaji Maharaj's letters order his officers and soldiers not to harass cultivators or take anything from them, not even a blade of grass. His administration gave farmers seed, bullocks and loans to bring land under the plough, and it measured and assessed land fairly." },
  { s: 1700, y: "c. 1600s onward", era: "medieval", mh: true, tag: "history", title: "Phad irrigation in the Tapi basin",
    text: "Farmers in the Panjhara, Mosam and Kan valleys of Dhule and Nashik built small stone weirs (bandharas) and shared canals, and grouped their fields into blocks called phads. Each season the community decided which crop each phad would grow. The system is centuries old and is still studied as a model of community water management." },
  { s: 1875, y: "1875", era: "colonial", mh: true, tag: "history", title: "The Deccan Riots",
    text: "In May 1875, peasants in Supe and other villages of Pune and Ahmednagar districts rose against moneylenders who had seized their land through debt. The unrest led to the Deccan Agriculturists' Relief Act of 1879." },
  { s: 1883, y: "1883", era: "colonial", mh: true, tag: "text", title: "Mahatma Phule's Shetkaryacha Asud",
    text: "In Shetkaryacha Asud (The Cultivator's Whipcord), Mahatma Jotirao Phule described the exploitation of farmers by moneylenders, officials and priests. He called for education for farmers' children, better seed and cattle, and irrigation." },
  { s: 1893, y: "1893", era: "colonial", tag: "history", title: "Voelcker praises the Indian cultivator",
    text: "John Augustus Voelcker, sent to advise the British government, wrote in his report 'Improvement of Indian Agriculture' that at his best the Indian cultivator was as good as, and in some respects better than, the average British farmer." },
  { s: 1905, y: "1905–1907", era: "colonial", mh: true, tag: "history", title: "Research institutions are founded",
    text: "The Imperial Agricultural Research Institute opened at Pusa in Bihar in 1905; it later moved to New Delhi and is now IARI. In Maharashtra, the College of Agriculture in Pune became a full college in 1907." },
  { s: 1931, y: "1924–1940", era: "colonial", tag: "science", title: "Albert Howard learns composting from Indian farmers",
    text: "At Indore, Sir Albert Howard developed the 'Indore method' of composting, drawing on practices he observed among Indian farmers. His book An Agricultural Testament (1940) helped launch the worldwide organic farming movement." },
  { s: 1937, y: "1928–1949", era: "colonial", mh: true, tag: "history", title: "Ending the Khoti system in Konkan",
    text: "Dr. B. R. Ambedkar led Konkan tenant farmers against the Khoti system, under which intermediaries collected rent and forced labour. He introduced a bill to abolish it in 1937, and the Bombay Khoti Abolition Act was passed in 1949." },
  { s: 1966, y: "1965–1970s", era: "independent", tag: "policy", title: "The Green Revolution",
    text: "High-yielding wheat and rice varieties, fertilisers and irrigation made India self-sufficient in food grains. The gains were large, but so were the costs: many traditional varieties disappeared, and soils and groundwater came under strain." },
  { s: 1970, y: "1970", era: "independent", tag: "policy", title: "Operation Flood",
    text: "The National Dairy Development Board launched Operation Flood, which built a nationwide network of milk co-operatives. India became the world's largest milk producer, and Maharashtra's co-operative dairies grew with it." },
  { s: 1972, y: "1972", era: "independent", mh: true, tag: "policy", title: "Maharashtra's Employment Guarantee Scheme",
    text: "During the severe drought of 1972–73, Maharashtra created the Employment Guarantee Scheme, which offered rural work building bunds, ponds and roads. It later inspired the national MGNREGA of 2005." },
  { s: 1985, y: "1975–2000", era: "independent", mh: true, tag: "history", title: "Village watershed models",
    text: "Ralegan Siddhi (from 1975) and Hiware Bazar (from the 1990s), both in Ahilyanagar district, revived their villages through watershed work, bans on free grazing and tree-felling, and collective decisions. They became national models." },
  { s: 2001, y: "2001–2006", era: "now", tag: "policy", title: "Laws that recognise traditional knowledge",
    text: "The Protection of Plant Varieties and Farmers' Rights Act (2001) recognises farmers as breeders and conservers of varieties. The Biological Diversity Act (2002) led to People's Biodiversity Registers in villages, and the Forest Rights Act (2006) recognised the rights of forest-dwelling communities." },
  { s: 2015, y: "2014–2016", era: "now", tag: "policy", title: "Gokul Mission, organic farming and soil health",
    text: "The Rashtriya Gokul Mission (2014) began supporting indigenous cattle breeds. Paramparagat Krishi Vikas Yojana (2015) promoted cluster-based organic farming, and Soil Health Cards (2015) gave farmers a record of their soil nutrients. Maharashtra started Jalyukt Shivar for village water conservation." },
  { s: 2023, y: "2023", era: "now", tag: "policy", title: "The International Year of Millets",
    text: "At India's proposal, the United Nations declared 2023 the International Year of Millets. The campaign revived interest in jowar, bajra, nachni and the small millets that tribal and dryland farmers of Maharashtra have grown for centuries." },
  { s: 2024, y: "November 2024", era: "now", tag: "policy", title: "The National Mission on Natural Farming",
    text: "The Union Cabinet approved the National Mission on Natural Farming on 25 November 2024, with an outlay of ₹2,481 crore. It aims to reach one crore farmers and bring 7.5 lakh hectares under natural farming through 15,000 clusters, drawing explicitly on traditional knowledge and local livestock." },
  { s: 2025, y: "October 2024 – February 2025", era: "now", tag: "policy", title: "The 21st Livestock Census",
    text: "The 21st Livestock Census counted 16 species, including dogs and elephants, and recorded 219 indigenous breeds recognised by ICAR-NBAGR. For the first time it also collected information on pastoralists and their animals. Its results had not been published when this archive was compiled." },
  { s: 2026, y: "March 2026", era: "now", mh: true, tag: "policy", title: "Economic Survey of Maharashtra 2025-26",
    text: "The latest Economic Survey, tabled on 5 March 2026, shows how Maharashtra's farming has changed. Jowar has fallen from 62.8 to 16.9 lakh hectares since 1960-61, while pulses have more than doubled, and livestock now contributes 23.4% of the value added by agriculture and allied sectors." }
];

/* Classical and historical texts on farming, animals and water */
const TEXTS = [
  { name: "Rigveda", dev: "ऋग्वेद", date: "c. 1500–1200 BCE", lang: "Vedic Sanskrit", topics: ["farming", "animals", "water"],
    summary: "The oldest Indian text. It praises the plough, the furrow and the rains, refers to wells and channels, and treats cattle as the chief form of wealth. The cow is called aghnya, 'not to be killed'.",
    refs: "4.57 (Kshetrapati hymn); 10.34.13 (advice to farm); 10.75 (hymn to the rivers); 10.101 (yoking the plough)",
    url: "https://www.sacred-texts.com/hin/rigveda/rv04057.htm" },
  { name: "Yajurveda", dev: "यजुर्वेद", date: "c. 1200–800 BCE", lang: "Vedic Sanskrit", topics: ["farming"],
    summary: "Records sacrificial rituals and, in doing so, lists the grains of the time, including rice, barley, wheat, pulses, sesame and several millets. The Taittiriya Samhita links crops to their seasons.",
    refs: "Vajasaneyi Samhita 18.12 (list of grains)" },
  { name: "Atharvaveda", dev: "अथर्ववेद", date: "c. 1000–800 BCE", lang: "Vedic Sanskrit", topics: ["farming", "animals", "water"],
    summary: "Closest of the Vedas to everyday life. It contains the Prithvi Sukta in praise of the Earth, prayers for rain, charms to protect cattle, and incantations against crop pests.",
    refs: "12.1 (Prithvi Sukta)", url: "https://www.sacred-texts.com/hin/av/av12001.htm" },
  { name: "Shatapatha Brahmana", dev: "शतपथ ब्राह्मण", date: "c. 800–600 BCE", lang: "Vedic Sanskrit", topics: ["farming"],
    summary: "Summarises farming as ploughing, sowing, reaping and threshing, and describes ploughing ceremonies with teams of oxen.",
    refs: "1.6.1.3" },
  { name: "Ashtadhyayi of Panini", dev: "अष्टाध्यायी", date: "c. 5th–4th century BCE", lang: "Sanskrit", topics: ["farming"],
    summary: "A grammar that preserves words for fields suited to particular crops, for ploughing, and for land measurement, showing how finely land was classified." },
  { name: "Arthashastra of Kautilya", dev: "अर्थशास्त्र", date: "compiled c. 4th century BCE – 3rd century CE", lang: "Sanskrit", topics: ["farming", "animals", "water"],
    summary: "A manual of statecraft. It describes state farms, seed preparation, rainfall measurement, regional rainfall (including Ashmaka on the Godavari), irrigation dues, and officials in charge of cattle, horses and elephants.",
    refs: "Book 2 (superintendents of agriculture, cattle, horses and elephants)" },
  { name: "Jataka tales", dev: "जातक कथा", date: "c. 4th century BCE onward", lang: "Pali", topics: ["farming", "animals", "water"],
    summary: "Buddhist stories that show daily village life, with shared irrigation channels, guarding of crops, cattle herding, and disputes over water." },
  { name: "Gatha Saptashati", dev: "गाथा सप्तशती", date: "c. 1st–3rd century CE", lang: "Maharashtri Prakrit", topics: ["farming", "animals"], mh: true,
    summary: "An anthology from the Satavahana Deccan. Its short poems describe cotton and rice fields, herders, threshing floors and the monsoon, making it an early literary portrait of Maharashtra's villages." },
  { name: "Sangam literature", dev: "संगम साहित्य", date: "c. 300 BCE – 300 CE", lang: "Old Tamil", topics: ["farming", "animals", "water"],
    summary: "Poetry that classifies land into five landscapes, each with its own crops, animals, occupations and seasons." },
  { name: "Tirukkural", dev: "तिरुक्कुरळ", date: "c. 5th century CE", lang: "Tamil", topics: ["farming"],
    summary: "Its chapter on farming (Uzhavu) calls agriculture the foremost occupation, because the whole world depends on it." },
  { name: "Brihat Samhita of Varahamihira", dev: "बृहत्संहिता", date: "6th century CE", lang: "Sanskrit", topics: ["farming", "animals", "water"],
    summary: "Covers monsoon forecasting from cloud and wind signs, locating groundwater from plants and termite mounds, tree care, and the features of good cattle.",
    refs: "Chapters on garbha lakshana, dakargala and vrikshayurveda" },
  { name: "Krishi-Parashara", dev: "कृषिपराशर", date: "dated c. 500–1100 CE", lang: "Sanskrit", topics: ["farming", "animals"],
    summary: "A practical manual on rain forecasting, the plough and its parts, cattle-shed hygiene, manure, and the collection and storage of seed. It opens by calling agriculture the source of prosperity." },
  { name: "Kashyapiya Krishisukti", dev: "काश्यपीय कृषिसूक्ति", date: "c. 8th–10th century CE", lang: "Sanskrit", topics: ["farming", "water"],
    summary: "Describes rice cultivation in detail: nursery beds, transplanting, water management and crop protection." },
  { name: "Vrikshayurveda of Surapala", dev: "वृक्षायुर्वेद", date: "c. 10th–11th century CE", lang: "Sanskrit", topics: ["farming"],
    summary: "A science of plant life covering soils, seed treatment, grafting, irrigation, plant diseases and kunapajala liquid manure." },
  { name: "Lokopakara of Chavundaraya II", dev: "लोकोपकार", date: "1025 CE", lang: "Kannada", topics: ["farming", "water"],
    summary: "A regional-language encyclopaedia with chapters on planting trees, divining groundwater and treating plant diseases." },
  { name: "Manasollasa of Someshvara III", dev: "मानसोल्लास", date: "1131 CE", lang: "Sanskrit", topics: ["farming", "animals", "water"], mh: true,
    summary: "A royal encyclopaedia from the Chalukya court, covering gardens, irrigation, horses, elephants and the breeding and training of dogs." },
  { name: "Upavanavinoda of Sarngadhara", dev: "उपवनविनोद", date: "13th–14th century CE", lang: "Sanskrit", topics: ["farming"],
    summary: "A treatise on orchards and gardens: soils, watering, grafting and the treatment of sick trees." },
  { name: "Shalihotra Samhita", dev: "शालिहोत्र संहिता", date: "traditionally ancient; manuscripts of later date", lang: "Sanskrit", topics: ["animals"],
    summary: "The foundational text of Indian veterinary science, especially the care and treatment of horses. 'Shalihotri' long remained a word for a veterinarian." },
  { name: "Hastyayurveda of Palakapya", dev: "हस्त्यायुर्वेद", date: "early centuries CE (disputed)", lang: "Sanskrit", topics: ["animals"],
    summary: "A detailed treatise on the anatomy, diseases and care of elephants." },
  { name: "Ain-i-Akbari of Abul Fazl", dev: "आईन-ए-अकबरी", date: "1590s", lang: "Persian", topics: ["farming"],
    summary: "Lists the crops of each province of the Mughal empire with their yields and prices, and explains Todar Mal's land-revenue system." },
  { name: "Dnyaneshwari and Varkari abhangs", dev: "ज्ञानेश्वरी व अभंग", date: "1290 CE onward", lang: "Marathi", topics: ["farming", "animals"], mh: true,
    summary: "Marathi saint-poets such as Dnyaneshwar, Namdev and Tukaram drew their images from the fields: sowing, rain, the plough and the cattle. Tukaram, himself from a farming and trading family of Dehu, sang of the farmer's life and of famine." },
  { name: "Shetkaryacha Asud by Jotirao Phule", dev: "शेतकऱ्याचा असूड", date: "1883", lang: "Marathi", topics: ["farming"], mh: true,
    summary: "A powerful account of the exploitation of Maharashtra's farmers, with practical proposals for irrigation, education and better cattle." },
  { name: "An Agricultural Testament by Albert Howard", dev: "ॲन ॲग्रिकल्चरल टेस्टामेंट", date: "1940", lang: "English", topics: ["farming"],
    summary: "Describes the Indore composting method, which Howard developed from the practices of Indian farmers. The book became a founding text of organic farming worldwide." }
];